import { useEffect, useState } from 'react';
import { AlertTriangle, Database, Search, ShieldCheck } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link, useLocation } from 'react-router-dom';
import Container from '../components/common/Container';
import Button from '../components/common/Button';
import AdminLayout from '../layouts/AdminLayout';
import { adminService } from '../services/adminService';

const date = (value) => value ? new Date(value).toLocaleDateString() : 'Not available';
const errorText = 'Unable to load this admin view.';

function Loading() { return <Container className="space-y-5 py-8"><div className="h-10 w-72 animate-pulse rounded bg-slate-200" /><div className="grid gap-4 md:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-slate-200" />)}</div><div className="h-72 animate-pulse rounded-2xl bg-slate-200" /></Container>; }
function ErrorState({ retry }) { return <Container className="py-16"><div className="mx-auto max-w-lg rounded-2xl border border-red-200 bg-red-50 p-8 text-center"><AlertTriangle className="mx-auto text-red-600" size={36} /><h2 className="mt-4 text-xl font-bold text-red-900">{errorText}</h2><Button onClick={retry} className="mt-5 rounded-xl">Try Again</Button></div></Container>; }
function Card({ title, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-bold text-slate-900">{title}</h2>{children}</section>; }
function Table({ headers, children }) { return <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map((header) => <th key={header} className="whitespace-nowrap px-4 py-3 font-bold">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div>; }
const CellText = ({ children }) => <td className="whitespace-nowrap px-4 py-3 text-slate-700">{children}</td>;

function AdminDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(false);
  const load = async () => { setError(false); try { setData(await adminService.getDashboard()); } catch { setError(true); } };
  useEffect(() => { load(); }, []);
  if (error) return <ErrorState retry={load} />; if (!data) return <Loading />;
  const stats = data.statistics;
  return <Container className="py-8"><header className="mb-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Administration</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Admin Dashboard</h1><p className="mt-2 text-slate-600">Live system activity and data overview.</p></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries({ 'Total Users': stats.totalUsers, 'Total Soil Analyses': stats.totalSoilAnalyses, 'Total Reports': stats.totalReports, 'Fertilizer Records': stats.totalFertilizerRecords, 'Crop Records': stats.totalCropRecords }).map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold text-slate-900">{value}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card title="Recent Registrations"><Table headers={['Name', 'Email', 'Role', 'Registered', 'Analyses']}>{data.recentRegistrations.map((user) => <tr key={user._id}><CellText>{user.name}</CellText><CellText>{user.email}</CellText><CellText>{user.role}</CellText><CellText>{date(user.createdAt)}</CellText><CellText>{user.analysisCount}</CellText></tr>)}</Table></Card><Card title="Recent Analyses"><Table headers={['User', 'Date', 'Crop', 'Fertility']}>{data.recentAnalyses.map((analysis) => <tr key={analysis._id}><CellText>{analysis.user?.name || 'Unknown'}</CellText><CellText>{date(analysis.createdAt)}</CellText><CellText>{analysis.crop}</CellText><CellText>{analysis.fertility || 'Not available'}</CellText></tr>)}</Table></Card></div></Container>;
}

function UsersView() {
  const [users, setUsers] = useState(null); const [search, setSearch] = useState(''); const [role, setRole] = useState('all'); const [error, setError] = useState(false);
  const load = async () => { setError(false); try { const result = await adminService.getUsers({ search, role }); setUsers(result.users); } catch { setError(true); } };
  useEffect(() => { load(); }, [role]);
  if (error) return <ErrorState retry={load} />; if (!users) return <Loading />;
  return <Container className="py-8"><header className="mb-8"><h1 className="text-3xl font-bold text-slate-900">Users</h1><p className="mt-2 text-slate-600">Safe account information for registered users.</p></header><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Search name or email" className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-3" /></label><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-xl border border-slate-300 px-3"><option value="all">All roles</option><option value="user">Users</option><option value="admin">Admins</option></select><Button onClick={load} className="rounded-xl">Search</Button></div><Table headers={['Name', 'Email', 'Role', 'Registration date', 'Analyses', 'View']}>{users.map((user) => <tr key={user._id}><CellText>{user.name}</CellText><CellText>{user.email}</CellText><CellText>{user.role}</CellText><CellText>{date(user.createdAt)}</CellText><CellText>{user.analysisCount}</CellText><CellText><Link className="font-semibold text-emerald-700" to={`/admin/users/${user._id}`}>View user</Link></CellText></tr>)}</Table></Container>;
}

function UserDetailView({ id }) {
  const [data, setData] = useState(null); const [error, setError] = useState(false); const load = async () => { try { setData(await adminService.getUser(id)); } catch { setError(true); } }; useEffect(() => { load(); }, [id]);
  if (error) return <ErrorState retry={load} />; if (!data) return <Loading />; return <Container className="py-8"><Link to="/admin/users" className="font-semibold text-emerald-700">← Back to users</Link><h1 className="mt-5 text-3xl font-bold text-slate-900">{data.user.name}</h1><p className="mt-2 text-slate-600">{data.user.email}</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5">Role<strong className="mt-2 block">{data.user.role}</strong></div><div className="rounded-2xl border bg-white p-5">Analyses<strong className="mt-2 block">{data.statistics.analysisCount}</strong></div><div className="rounded-2xl border bg-white p-5">Reports<strong className="mt-2 block">{data.statistics.reportCount}</strong></div></div><Card title="Recent activity"><Table headers={['Date', 'Crop', 'Soil type', 'Status']}>{data.recentActivity.map((item) => <tr key={item._id}><CellText>{date(item.createdAt)}</CellText><CellText>{item.crop}</CellText><CellText>{item.soilType}</CellText><CellText>{item.status}</CellText></tr>)}</Table></Card></Container>;
}

function AnalysesView() { const [data, setData] = useState(null); const [error, setError] = useState(false); const load = async () => { try { setData(await adminService.getAnalyses()); } catch { setError(true); } }; useEffect(() => { load(); }, []); if (error) return <ErrorState retry={load} />; if (!data) return <Loading />; return <Container className="py-8"><h1 className="mb-2 text-3xl font-bold text-slate-900">Soil Analyses</h1><p className="mb-8 text-slate-600">View stored analyses and derived scores. Predictions are read-only.</p><Table headers={['Analysis ID', 'User', 'Date', 'Crop', 'Soil type', 'Fertility', 'Health score']}>{data.analyses.map((item) => <tr key={item._id}><CellText>{item._id}</CellText><CellText>{item.user?.name || 'Unknown'}</CellText><CellText>{date(item.createdAt)}</CellText><CellText>{item.crop}</CellText><CellText>{item.soilType}</CellText><CellText>{item.fertility || 'Not available'}</CellText><CellText>{item.soilHealthScore === null ? 'Not available' : `${item.soilHealthScore}/100`}</CellText></tr>)}</Table></Container>; }

function ReportsView() { const [data, setData] = useState(null); const [error, setError] = useState(false); const load = async () => { try { setData(await adminService.getReports()); } catch { setError(true); } }; useEffect(() => { load(); }, []); if (error) return <ErrorState retry={load} />; if (!data) return <Loading />; return <Container className="py-8"><h1 className="mb-2 text-3xl font-bold text-slate-900">Reports</h1><p className="mb-8 text-slate-600">Report metadata derived from analyzed records.</p><Table headers={['Report ID', 'User', 'Analysis date', 'Fertility', 'Health score', 'Generated']}>{data.reports.map((item) => <tr key={item.analysisId}><CellText>{item.reportId}</CellText><CellText>{item.user?.name || 'Unknown'}</CellText><CellText>{date(item.analysisDate)}</CellText><CellText>{item.fertility || 'Not available'}</CellText><CellText>{item.soilHealthScore === null ? 'Not available' : `${item.soilHealthScore}/100`}</CellText><CellText>{date(item.generatedAt)}</CellText></tr>)}</Table></Container>; }

function StaticDataView({ type }) { const [data, setData] = useState(null); const load = async () => setData(type === 'fertilizers' ? await adminService.getFertilizers() : await adminService.getCrops()); useEffect(() => { load(); }, []); if (!data) return <Loading />; const records = type === 'fertilizers' ? data.fertilizers : data.crops; return <Container className="py-8"><h1 className="text-3xl font-bold capitalize text-slate-900">{type}</h1><p className="mt-2 mb-6 text-slate-600">{data.message}</p><Table headers={type === 'fertilizers' ? ['Name', 'Category', 'Type', 'Purpose'] : ['Name', 'Category', 'Season', 'Soil types']}>{records.map((item) => <tr key={item.id}><CellText>{item.name}</CellText><CellText>{item.category}</CellText><CellText>{type === 'fertilizers' ? item.type : item.season}</CellText><CellText>{type === 'fertilizers' ? item.purpose : item.suitableSoilTypes?.join(', ')}</CellText></tr>)}</Table></Container>; }

function AnalyticsView() { const [data, setData] = useState(null); const [error, setError] = useState(false); const load = async () => { try { setData(await adminService.getAnalytics()); } catch { setError(true); } }; useEffect(() => { load(); }, []); if (error) return <ErrorState retry={load} />; if (!data) return <Loading />; const fertility = data.fertility.map((item) => ({ name: item._id || 'Unknown', count: item.count })); return <Container className="py-8"><h1 className="mb-8 text-3xl font-bold text-slate-900">System Analytics</h1><div className="grid gap-6 lg:grid-cols-2"><Card title="User registrations over time"><Chart data={data.registrations} /></Card><Card title="Soil analyses over time"><Chart data={data.analyses} /></Card><Card title="Fertility distribution"><div className="h-64">{fertility.length ? <ResponsiveContainer><PieChart><Pie data={fertility} dataKey="count" nameKey="name" outerRadius={90} label>{fertility.map((entry, index) => <Cell key={entry.name} fill={['#059669', '#0ea5e9', '#f59e0b'][index % 3]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer> : <p className="text-sm text-slate-600">No fertility data available.</p>}</div></Card><Card title="Most analyzed crops"><Chart data={data.crops} labelKey="_id" /></Card></div></Container>; }
function Chart({ data, labelKey = '_id' }) { if (!data.length) return <p className="text-sm text-slate-600">No data available.</p>; return <div className="h-64"><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey={labelKey} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" fill="#059669" /></BarChart></ResponsiveContainer></div>; }
function SettingsView() { const [data, setData] = useState(null); useEffect(() => { adminService.getSettings().then(setData); }, []); if (!data) return <Loading />; return <Container className="py-8"><h1 className="mb-8 text-3xl font-bold text-slate-900">Admin Settings</h1><div className="grid gap-4 sm:grid-cols-2">{Object.entries(data.settings).map(([key, value]) => <div key={key} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{key}</p><p className="mt-3 font-semibold text-slate-900">{value}</p></div>)}</div><div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900"><ShieldCheck className="mb-2" size={20} />Secrets and private credentials are never displayed.</div></Container>; }

export default function AdminPage() { const location = useLocation(); const path = location.pathname; let view = <AdminDashboard />; if (path === '/admin/users') view = <UsersView />; else if (path.startsWith('/admin/users/')) view = <UserDetailView id={path.split('/').pop()} />; else if (path === '/admin/soil-analyses') view = <AnalysesView />; else if (path === '/admin/fertilizers') view = <StaticDataView type="fertilizers" />; else if (path === '/admin/crops') view = <StaticDataView type="crops" />; else if (path === '/admin/reports') view = <ReportsView />; else if (path === '/admin/analytics') view = <AnalyticsView />; else if (path === '/admin/settings') view = <SettingsView />; return <AdminLayout>{view}</AdminLayout>; }
